/**
 * Script to generate theme assets from centralized colors and breakpoints
 * This ensures single source of truth for all theme values
 */

import { sagaBlueColors, generateCSSVariables, generateTailwindColors } from '../colors/saga-blue-colors';
import * as fs from 'fs';
import * as path from 'path';

/**
 * Generate CSS variables file
 */
function generateCSSVariablesFile() {
  const cssVariables = generateCSSVariables(sagaBlueColors);

  let cssContent = `/**
 * Saga-Blue Theme CSS Variables
 * Auto-generated from centralized color system
 * DO NOT EDIT MANUALLY - Edit saga-blue-colors.ts instead
 */

@layer base {
  :root {
`;

  // Add all CSS variables
  for (const [varName, value] of Object.entries(cssVariables)) {
    cssContent += `    ${varName}: ${value};\n`;
  }

  cssContent += `
    /* Focus ring */
    --focus-ring: 0 0 0 0.2rem ${sagaBlueColors.blue[200]};

    /* Highlight colors */
    --highlight-bg: ${sagaBlueColors.blue[50]};
    --highlight-text-color: ${sagaBlueColors.text.primary};

    /* Mask/overlay */
    --maskbg: rgba(0, 0, 0, 0.4);

    /* Spacing */
    --content-padding: 1rem;
    --inline-spacing: 0.5rem;

    /* Border radius */
    --border-radius: 3px;

    /* Font family */
    --font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";

    /* Color scheme */
    color-scheme: light;
  }
}

/* PrimeNG Tabs customization - CSS variables override (outside layer to load after PrimeNG styles) */
:root, :host {
  --p-tabs-tabpanel-background: transparent;
  --p-tabs-tabpanel-padding: var(--spacing-3) var(--spacing-2);
}

/* Layer 2: Component styles */
@layer components {
  /* Custom scroll panel styles */
  .p-scrollpanel.custombar1 .p-scrollpanel-wrapper {
    border-right: 9px solid var(--surface-card);
  }

  .p-scrollpanel.custombar1 .p-scrollpanel-bar {
    background-color: var(--primary-color);
    opacity: 1;
    transition: background-color 0.2s;
  }

  .p-scrollpanel.custombar1 .p-scrollpanel-bar:hover {
    background-color: #007ad9;
  }

  .p-scrollpanel.custombar2 .p-scrollpanel-wrapper {
    border-right: 9px solid var(--surface-card);
  }

  .p-scrollpanel.custombar2 .p-scrollpanel-bar {
    background-color: ${sagaBlueColors.purple[500]};
    border-radius: 0;
    opacity: 1;
    transition: background-color 0.2s;
  }

  /* Overlay styles */
  .p-component-overlay {
    background-color: ${sagaBlueColors.blue[50]}60;
  }

  /* DataTable styles */
  .p-datatable .p-datatable-tbody > tr.pg-no-hover,
  .p-datatable .p-datatable-tbody > tr.pg-no-hover:hover {
    background: transparent !important;
    box-shadow: none !important;
  }

  .p-datatable .p-datatable-tbody > tr.pg-no-hover > td {
    cursor: auto !important;
    border: 0;
    padding: 0;
  }

  /* Button fluid styles */
  .p-fluid .p-button {
    /* width: auto; - commented out as per original */
  }
}

/* Layer 3: Utilities */
@layer utilities {
  /* Required field indicator */
  .p-required:after {
    content: "*";
    color: ${sagaBlueColors.red[600]};
  }

  /* Visually hidden for accessibility */
  .visually-hidden {
    position: absolute !important;
    width: 1px !important;
    height: 1px !important;
    padding: 0 !important;
    margin: -1px !important;
    overflow: hidden !important;
    clip: rect(0 0 0 0) !important;
    white-space: nowrap !important;
    border: 0 !important;
  }

  /* Plotly mode bar hiding */
  .modebar-container {
    display: none;
  }
}

/* Layer 4: Base styles */
@layer base {
  html, body {
    height: 100%;
    width: 100%;
    padding: 0;
    margin: 0;
  }

  html {
    font-size: 1rem;
  }

  body {
    font-family: var(--font-family);
    background-color: var(--surface-ground);
    color: var(--text-color);
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    display: flex;
    flex-direction: column;
  }
}`;

  const outputPath = path.join(__dirname, '../styles/saga-blue-layers.css');
  fs.writeFileSync(outputPath, cssContent);
}

/**
 * Generate breakpoints SCSS file
 */
function generateBreakpointsFile() {
  const breakpointsContent = `// Pegasus Design System - Centralized Breakpoints
// This file provides a single source of truth for all breakpoints across the application
// Auto-generated by the theme system - DO NOT EDIT MANUALLY

@use 'sass:map';

// =============================================================================
// BREAKPOINT DEFINITIONS
// =============================================================================

// Comprehensive breakpoints system
// Combines Tailwind CSS, PrimeFlex, and custom breakpoints for maximum compatibility

// Standard breakpoints (Tailwind CSS defaults + PrimeFlex compatibility)
$breakpoints: (
  'xs': 0px,        // Extra small devices (phones)
  'sm': 576px,      // Small devices (PrimeFlex compatibility)
  'md': 768px,      // Medium devices (tablets)
  'lg': 992px,      // Large devices (PrimeFlex compatibility)
  'xl': 1200px,     // Extra large devices (PrimeFlex compatibility)
  '2xl': 1536px,    // 2X large devices (ultra-wide screens)
  '3xl': 1920px     // 3X large devices (4K displays)
);

// Tailwind CSS specific breakpoints (for utility classes)
$tailwind-breakpoints: (
  'sm': 640px,      // Tailwind small
  'md': 768px,      // Tailwind medium
  'lg': 1024px,     // Tailwind large
  'xl': 1280px,     // Tailwind extra large
  '2xl': 1536px     // Tailwind 2X large
);

// Semantic breakpoints for better readability
$semantic-breakpoints: (
  'mobile': 576px,      // Mobile devices (PrimeFlex)
  'tablet': 768px,      // Tablet devices
  'laptop': 992px,      // Laptop devices (PrimeFlex)
  'desktop': 1200px,    // Desktop devices (PrimeFlex)
  'wide': 1536px,       // Wide desktop devices
  'ultra-wide': 1920px // Ultra-wide displays
);

// =============================================================================
// BREAKPOINT MIXINS
// =============================================================================

// Mobile-first approach (min-width)
@mixin xs-up {
  @media (min-width: map.get($breakpoints, 'xs')) {
    @content;
  }
}

@mixin sm-up {
  @media (min-width: map.get($breakpoints, 'sm')) {
    @content;
  }
}

@mixin md-up {
  @media (min-width: map.get($breakpoints, 'md')) {
    @content;
  }
}

@mixin lg-up {
  @media (min-width: map.get($breakpoints, 'lg')) {
    @content;
  }
}

@mixin xl-up {
  @media (min-width: map.get($breakpoints, 'xl')) {
    @content;
  }
}

@mixin xxl-up {
  @media (min-width: map.get($breakpoints, '2xl')) {
    @content;
  }
}

@mixin xxxl-up {
  @media (min-width: map.get($breakpoints, '3xl')) {
    @content;
  }
}

// Semantic mixins for better readability
@mixin mobile-up {
  @media (min-width: map.get($semantic-breakpoints, 'mobile')) {
    @content;
  }
}

@mixin tablet-up {
  @media (min-width: map.get($semantic-breakpoints, 'tablet')) {
    @content;
  }
}

@mixin laptop-up {
  @media (min-width: map.get($semantic-breakpoints, 'laptop')) {
    @content;
  }
}

@mixin desktop-up {
  @media (min-width: map.get($semantic-breakpoints, 'desktop')) {
    @content;
  }
}

@mixin wide-up {
  @media (min-width: map.get($semantic-breakpoints, 'wide')) {
    @content;
  }
}

@mixin ultra-wide-up {
  @media (min-width: map.get($semantic-breakpoints, 'ultra-wide')) {
    @content;
  }
}

// Desktop-first approach (max-width)
@mixin mobile-down {
  @media (max-width: map.get($breakpoints, 'sm') - 1px) {
    @content;
  }
}

@mixin tablet-down {
  @media (max-width: map.get($breakpoints, 'md') - 1px) {
    @content;
  }
}

@mixin desktop-down {
  @media (max-width: map.get($breakpoints, 'lg') - 1px) {
    @content;
  }
}

@mixin xl-down {
  @media (max-width: map.get($breakpoints, 'xl') - 1px) {
    @content;
  }
}

// Range-based breakpoints
@mixin tablet-only {
  @media (min-width: map.get($breakpoints, 'md')) and (max-width: map.get($breakpoints, 'lg') - 1px) {
    @content;
  }
}

@mixin desktop-only {
  @media (min-width: map.get($breakpoints, 'lg')) and (max-width: map.get($breakpoints, 'xl') - 1px) {
    @content;
  }
}

// =============================================================================
// UTILITY FUNCTIONS
// =============================================================================

// Get breakpoint value
@function breakpoint($name) {
  @return map.get($breakpoints, $name);
}

// Get semantic breakpoint value
@function semantic-breakpoint($name) {
  @return map.get($semantic-breakpoints, $name);
}

// Check if breakpoint exists
@function breakpoint-exists($name) {
  @return map.has-key($breakpoints, $name);
}

// =============================================================================
// RESPONSIVE MIXINS
// =============================================================================

// Responsive container with consistent padding
@mixin responsive-container {
  padding-left: var(--spacing-3);
  padding-right: var(--spacing-3);

  @include mobile-up {
    padding-left: var(--spacing-4);
    padding-right: var(--spacing-4);
  }

  @include tablet-up {
    padding-left: var(--spacing-5);
    padding-right: var(--spacing-5);
  }

  @include desktop-up {
    padding-left: var(--spacing-6);
    padding-right: var(--spacing-6);
  }

  @include wide-up {
    padding-left: var(--spacing-8);
    padding-right: var(--spacing-8);
  }
}

// Responsive typography scaling
@mixin responsive-typography($base-size, $scale-factor: 1.2) {
  font-size: $base-size;

  @include mobile-up {
    font-size: calc(#{$base-size} * #{$scale-factor});
  }

  @include desktop-up {
    font-size: calc(#{$base-size} * #{$scale-factor} * #{$scale-factor});
  }
}

// Responsive grid columns
@mixin responsive-grid($mobile: 1, $tablet: 2, $desktop: 3, $wide: 4) {
  display: grid;
  grid-template-columns: repeat($mobile, 1fr);
  gap: var(--spacing-4);

  @include mobile-up {
    grid-template-columns: repeat($tablet, 1fr);
    gap: var(--spacing-5);
  }

  @include desktop-up {
    grid-template-columns: repeat($desktop, 1fr);
    gap: var(--spacing-6);
  }

  @include wide-up {
    grid-template-columns: repeat($wide, 1fr);
    gap: var(--spacing-8);
  }
}`;

  const outputPath = path.join(__dirname, '../styles/breakpoints.scss');
  fs.writeFileSync(outputPath, breakpointsContent);
  console.log('✅ Generated breakpoints.scss');
}

/**
 * Generate Tailwind config
 */
function generateTailwindConfig() {
  const tailwindColors = generateTailwindColors(sagaBlueColors);

  const config = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './projects/**/*.{html,ts,mdx}',     // Angular templates + stories
    './**/*.stories.@(ts|mdx)'           // extra guard for SB stories
  ],
  theme: {
    // Comprehensive breakpoints system
    screens: {
      'xs': '0px',        // Extra small devices
      'sm': '576px',     // Small devices (PrimeFlex compatibility)
      'md': '768px',     // Medium devices
      'lg': '992px',     // Large devices (PrimeFlex compatibility)
      'xl': '1200px',    // Extra large devices (PrimeFlex compatibility)
      '2xl': '1536px',   // 2X large devices
      '3xl': '1920px'    // 3X large devices (4K displays)
    },
    extend: {
      // PrimeFlex-compatible spacing scale
      spacing: {
        '0': '0rem',     // 0px
        '1': '0.25rem',  // 4px
        '2': '0.5rem',   // 8px (--inline-spacing)
        '3': '1rem',     // 16px (--content-padding + PrimeFlex p-3)
        '4': '1.5rem',   // 24px (PrimeFlex p-4)
        '5': '2rem',     // 32px (PrimeFlex p-5)
        '6': '3rem',     // 48px (PrimeFlex p-6)
        '7': '4rem',     // 64px (PrimeFlex p-7)
        '8': '5rem',     // 80px (PrimeFlex p-8)
      },
      colors: ${JSON.stringify(tailwindColors, null, 6)},
      // Surface colors
      'surface': {
        'ground': '#f8f9fa',
        'section': '#ffffff',
        'card': '#ffffff',
        'overlay': '#ffffff',
        'border': '#dee2e6',
        'hover': '#e9ecef'
      },
      // Text colors
      'text': {
        'primary': '#495057',
        'secondary': '#6c757d',
        'disabled': '#adb5bd'
      },
      // PrimeNG surface colors for Tailwind utilities
      'surface-section': '#ffffff'
    }
  },
  plugins: [require('tailwindcss-primeui')]
};`;

  const outputPath = path.join(__dirname, '../../../tailwind.config.js');
  fs.writeFileSync(outputPath, config);
}

/**
 * Main execution
 */
if (require.main === module) {
  generateCSSVariablesFile();
  generateBreakpointsFile();
  generateTailwindConfig();
}
