import { Region, TrialCountry, TrialCountryDictionary } from '@country/country';
import { InjectionToken } from '@angular/core';
import {MeterItem} from 'primeng/metergroup';


export const trialCountries: TrialCountry[] = [
  { code: 'AF', code3: 'AFG', name: 'Afghanistan', countryNumber: '004' },
  { code: 'AX', code3: 'ALA', name: 'Aland Islands', countryNumber: '248' },
  { code: 'AL', code3: 'ALB', name: 'Albania', countryNumber: '008' },
  { code: 'DZ', code3: 'DZA', name: 'Algeria', countryNumber: '012' },
  { code: 'AS', code3: 'ASM', name: 'American Samoa', countryNumber: '016' },
  { code: 'AD', code3: 'AND', name: 'Andorra', countryNumber: '020' },
  { code: 'AO', code3: 'AGO', name: 'Angola', countryNumber: '024' },
  { code: 'AI', code3: 'AIA', name: 'Anguilla', countryNumber: '660' },
  { code: 'AQ', code3: 'ATA', name: 'Antarctica', countryNumber: '010' },
  {
    code: 'AG',
    code3: 'ATG',
    name: 'Antigua and Barbuda',
    countryNumber: '028',
  },
  { code: 'AR', code3: 'ARG', name: 'Argentina', countryNumber: '032' },
  { code: 'AM', code3: 'ARM', name: 'Armenia', countryNumber: '051' },
  { code: 'AW', code3: 'ABW', name: 'Aruba', countryNumber: '533' },
  { code: 'AU', code3: 'AUS', name: 'Australia', countryNumber: '036' },
  { code: 'AT', code3: 'AUT', name: 'Austria', countryNumber: '040' },
  { code: 'AZ', code3: 'AZE', name: 'Azerbaijan', countryNumber: '031' },
  { code: 'BS', code3: 'BHS', name: 'Bahamas', countryNumber: '044' },
  { code: 'BH', code3: 'BHR', name: 'Bahrain', countryNumber: '048' },
  { code: 'BD', code3: 'BGD', name: 'Bangladesh', countryNumber: '050' },
  { code: 'BB', code3: 'BRB', name: 'Barbados', countryNumber: '052' },
  { code: 'BY', code3: 'BLR', name: 'Belarus', countryNumber: '112' },
  { code: 'BE', code3: 'BEL', name: 'Belgium', countryNumber: '056' },
  { code: 'BZ', code3: 'BLZ', name: 'Belize', countryNumber: '084' },
  { code: 'BJ', code3: 'BEN', name: 'Benin', countryNumber: '204' },
  { code: 'BM', code3: 'BMU', name: 'Bermuda', countryNumber: '060' },
  { code: 'BT', code3: 'BTN', name: 'Bhutan', countryNumber: '064' },
  { code: 'BO', code3: 'BOL', name: 'Bolivia', countryNumber: '068' },
  { code: 'BQ', code3: 'BES', name: 'Bonaire', countryNumber: '535' },
  {
    code: 'BA',
    code3: 'BIH',
    name: 'Bosnia and Herzegovina',
    countryNumber: '070',
  },
  { code: 'BW', code3: 'BWA', name: 'Botswana', countryNumber: '072' },
  { code: 'BV', code3: 'BVT', name: 'Bouvet Island', countryNumber: '074' },
  { code: 'BR', code3: 'BRA', name: 'Brazil', countryNumber: '076' },
  {
    code: 'IO',
    code3: 'IOT',
    name: 'British Indian Ocean',
    countryNumber: '086',
  },
  { code: 'BN', code3: 'BRN', name: 'Brunei Darussalam', countryNumber: '096' },
  { code: 'BG', code3: 'BGR', name: 'Bulgaria', countryNumber: '100' },
  { code: 'BF', code3: 'BFA', name: 'Burkina Faso', countryNumber: '854' },
  { code: 'BI', code3: 'BDI', name: 'Burundi', countryNumber: '108' },
  { code: 'CV', code3: 'CPV', name: 'Cabo Verde', countryNumber: '132' },
  { code: 'KH', code3: 'KHM', name: 'Cambodia', countryNumber: '116' },
  { code: 'CM', code3: 'CMR', name: 'Cameroon', countryNumber: '120' },
  { code: 'CA', code3: 'CAN', name: 'Canada', countryNumber: '124' },
  { code: 'CV', code3: 'CPV', name: 'Cape Verde', countryNumber: '132' },
  { code: 'KY', code3: 'CYM', name: 'Cayman Islands', countryNumber: '136' },
  {
    code: 'CF',
    code3: 'CAF',
    name: 'Central African Republic',
    countryNumber: '140',
  },
  { code: 'TD', code3: 'TCD', name: 'Chad', countryNumber: '148' },
  { code: 'CL', code3: 'CHL', name: 'Chile', countryNumber: '152' },
  { code: 'CN', code3: 'CHN', name: 'China', countryNumber: '156' },
  { code: 'CX', code3: 'CXR', name: 'Christmas Island', countryNumber: '162' },
  { code: 'CC', code3: 'CCK', name: 'Cocos Islands', countryNumber: '166' },
  { code: 'CO', code3: 'COL', name: 'Colombia', countryNumber: '170' },
  { code: 'KM', code3: 'COM', name: 'Comoros', countryNumber: '174' },
  { code: 'CD', code3: 'COD', name: 'Congo, Kinshasa', countryNumber: '180' },
  {
    code: 'CG',
    code3: 'COG',
    name: 'Congo, Brazzaville',
    countryNumber: '178',
  },
  { code: 'CK', code3: 'COK', name: 'Cook Islands', countryNumber: '184' },
  { code: 'CR', code3: 'CRI', name: 'Costa Rica', countryNumber: '188' },
  { code: 'HR', code3: 'HRV', name: 'Croatia', countryNumber: '191' },
  { code: 'CU', code3: 'CUB', name: 'Cuba', countryNumber: '192' },
  { code: 'CW', code3: 'CUW', name: 'Curaçao', countryNumber: '531' },
  { code: 'CY', code3: 'CYP', name: 'Cyprus', countryNumber: '196' },
  { code: 'CZ', code3: 'CZE', name: 'Czech Republic', countryNumber: '203' },
  { code: 'CI', code3: 'CIV', name: "Côte d'Ivoire", countryNumber: '384' },
  { code: 'DK', code3: 'DNK', name: 'Denmark', countryNumber: '208' },
  { code: 'DJ', code3: 'DJI', name: 'Djibouti', countryNumber: '262' },
  { code: 'DM', code3: 'DMA', name: 'Dominica', countryNumber: '212' },
  {
    code: 'DO',
    code3: 'DOM',
    name: 'Dominican Republic',
    countryNumber: '214',
  },
  { code: 'EC', code3: 'ECU', name: 'Ecuador', countryNumber: '218' },
  { code: 'EG', code3: 'EGY', name: 'Egypt', countryNumber: '818' },
  { code: 'SV', code3: 'SLV', name: 'El Salvador', countryNumber: '222' },
  { code: 'GQ', code3: 'GNQ', name: 'Equatorial Guinea', countryNumber: '226' },
  { code: 'ER', code3: 'ERI', name: 'Eritrea', countryNumber: '232' },
  { code: 'EE', code3: 'EST', name: 'Estonia', countryNumber: '233' },
  { code: 'SZ', code3: 'SWZ', name: 'Eswatini', countryNumber: '748' },
  { code: 'ET', code3: 'ETH', name: 'Ethiopia', countryNumber: '231' },
  { code: 'FK', code3: 'FLK', name: 'Falkland Islands', countryNumber: '238' },
  { code: 'FO', code3: 'FRO', name: 'Faroe Islands', countryNumber: '234' },
  { code: 'FJ', code3: 'FJI', name: 'Fiji', countryNumber: '242' },
  { code: 'FI', code3: 'FIN', name: 'Finland', countryNumber: '246' },
  { code: 'FR', code3: 'FRA', name: 'France', countryNumber: '250' },
  { code: 'GF', code3: 'GUF', name: 'French Guiana', countryNumber: '254' },
  { code: 'PF', code3: 'PYF', name: 'French Polynesia', countryNumber: '258' },
  {
    code: 'TF',
    code3: 'ATF',
    name: 'French Southern Territories',
    countryNumber: '260',
  },
  { code: 'GA', code3: 'GAB', name: 'Gabon', countryNumber: '266' },
  { code: 'GM', code3: 'GMB', name: 'Gambia', countryNumber: '270' },
  { code: 'GE', code3: 'GEO', name: 'Georgia', countryNumber: '268' },
  { code: 'DE', code3: 'DEU', name: 'Germany', countryNumber: '276' },
  { code: 'GH', code3: 'GHA', name: 'Ghana', countryNumber: '288' },
  { code: 'GI', code3: 'GIB', name: 'Gibraltar', countryNumber: '292' },
  { code: 'GR', code3: 'GRC', name: 'Greece', countryNumber: '300' },
  { code: 'GL', code3: 'GRL', name: 'Greenland', countryNumber: '304' },
  { code: 'GD', code3: 'GRD', name: 'Grenada', countryNumber: '308' },
  { code: 'GP', code3: 'GLP', name: 'Guadeloupe', countryNumber: '312' },
  { code: 'GU', code3: 'GUM', name: 'Guam', countryNumber: '316' },
  { code: 'GT', code3: 'GTM', name: 'Guatemala', countryNumber: '320' },
  { code: 'GG', code3: 'GGY', name: 'Guernsey', countryNumber: '831' },
  { code: 'GN', code3: 'GIN', name: 'Guinea', countryNumber: '324' },
  { code: 'GW', code3: 'GNB', name: 'Guinea-Bissau', countryNumber: '624' },
  { code: 'GY', code3: 'GUY', name: 'Guyana', countryNumber: '328' },
  { code: 'HT', code3: 'HTI', name: 'Haiti', countryNumber: '332' },
  {
    code: 'HM',
    code3: 'HMD',
    name: 'Heard Island, McDonald Islands',
    countryNumber: '334',
  },
  { code: 'VA', code3: 'VAT', name: 'Holy See', countryNumber: '336' },
  { code: 'HN', code3: 'HND', name: 'Honduras', countryNumber: '340' },
  { code: 'HK', code3: 'HKG', name: 'Hong Kong', countryNumber: '344' },
  { code: 'HU', code3: 'HUN', name: 'Hungary', countryNumber: '348' },
  { code: 'IS', code3: 'ISL', name: 'Iceland', countryNumber: '352' },
  { code: 'IN', code3: 'IND', name: 'India', countryNumber: '356' },
  { code: 'ID', code3: 'IDN', name: 'Indonesia', countryNumber: '360' },
  { code: 'IR', code3: 'IRN', name: 'Iran', countryNumber: '364' },
  { code: 'IQ', code3: 'IRQ', name: 'Iraq', countryNumber: '368' },
  { code: 'IE', code3: 'IRL', name: 'Ireland', countryNumber: '372' },
  { code: 'IM', code3: 'IMN', name: 'Isle of Man', countryNumber: '833' },
  { code: 'IL', code3: 'ISR', name: 'Israel', countryNumber: '376' },
  { code: 'IT', code3: 'ITA', name: 'Italy', countryNumber: '380' },
  { code: 'JM', code3: 'JAM', name: 'Jamaica', countryNumber: '388' },
  { code: 'JP', code3: 'JPN', name: 'Japan', countryNumber: '392' },
  { code: 'JE', code3: 'JEY', name: 'Jersey', countryNumber: '832' },
  { code: 'JO', code3: 'JOR', name: 'Jordan', countryNumber: '400' },
  { code: 'KZ', code3: 'KAZ', name: 'Kazakhstan', countryNumber: '398' },
  { code: 'KE', code3: 'KEN', name: 'Kenya', countryNumber: '404' },
  { code: 'KI', code3: 'KIR', name: 'Kiribati', countryNumber: '296' },
  {
    code: 'KR',
    code3: 'KOR',
    name: 'South Korea',
    countryNumber: '410',
  },
  { code: 'KW', code3: 'KWT', name: 'Kuwait', countryNumber: '414' },
  { code: 'KG', code3: 'KGZ', name: 'Kyrgyzstan', countryNumber: '417' },
  { code: 'LA', code3: 'LAO', name: "Lao's", countryNumber: '418' },
  { code: 'LV', code3: 'LVA', name: 'Latvia', countryNumber: '428' },
  { code: 'LB', code3: 'LBN', name: 'Lebanon', countryNumber: '422' },
  { code: 'LS', code3: 'LSO', name: 'Lesotho', countryNumber: '426' },
  { code: 'LR', code3: 'LBR', name: 'Liberia', countryNumber: '430' },
  { code: 'LY', code3: 'LBY', name: 'Libya', countryNumber: '434' },
  { code: 'LI', code3: 'LIE', name: 'Liechtenstein', countryNumber: '438' },
  { code: 'LT', code3: 'LTU', name: 'Lithuania', countryNumber: '440' },
  { code: 'LU', code3: 'LUX', name: 'Luxembourg', countryNumber: '442' },
  { code: 'MO', code3: 'MAC', name: 'Macao', countryNumber: '446' },
  { code: 'MG', code3: 'MDG', name: 'Madagascar', countryNumber: '450' },
  { code: 'MW', code3: 'MWI', name: 'Malawi', countryNumber: '454' },
  { code: 'MY', code3: 'MYS', name: 'Malaysia', countryNumber: '458' },
  { code: 'MV', code3: 'MDV', name: 'Maldives', countryNumber: '462' },
  { code: 'ML', code3: 'MLI', name: 'Mali', countryNumber: '466' },
  { code: 'MT', code3: 'MLT', name: 'Malta', countryNumber: '470' },
  { code: 'MH', code3: 'MHL', name: 'Marshall Islands', countryNumber: '584' },
  { code: 'MQ', code3: 'MTQ', name: 'Martinique', countryNumber: '474' },
  { code: 'MR', code3: 'MRT', name: 'Mauritania', countryNumber: '478' },
  { code: 'MU', code3: 'MUS', name: 'Mauritius', countryNumber: '480' },
  { code: 'YT', code3: 'MYT', name: 'Mayotte', countryNumber: '175' },
  { code: 'MX', code3: 'MEX', name: 'Mexico', countryNumber: '484' },
  { code: 'FM', code3: 'FSM', name: 'Micronesia', countryNumber: '583' },
  { code: 'MD', code3: 'MDA', name: 'Moldova', countryNumber: '498' },
  { code: 'MC', code3: 'MCO', name: 'Monaco', countryNumber: '492' },
  { code: 'MN', code3: 'MNG', name: 'Mongolia', countryNumber: '496' },
  { code: 'ME', code3: 'MNE', name: 'Montenegro', countryNumber: '499' },
  { code: 'MS', code3: 'MSR', name: 'Montserrat', countryNumber: '500' },
  { code: 'MA', code3: 'MAR', name: 'Morocco', countryNumber: '504' },
  { code: 'MZ', code3: 'MOZ', name: 'Mozambique', countryNumber: '508' },
  { code: 'MM', code3: 'MMR', name: 'Myanmar', countryNumber: '104' },
  { code: 'NA', code3: 'NAM', name: 'Namibia', countryNumber: '516' },
  { code: 'NR', code3: 'NRU', name: 'Nauru', countryNumber: '520' },
  { code: 'NP', code3: 'NPL', name: 'Nepal', countryNumber: '524' },
  { code: 'NL', code3: 'NLD', name: 'Netherlands', countryNumber: '528' },
  { code: 'NC', code3: 'NCL', name: 'New Caledonia', countryNumber: '540' },
  { code: 'NZ', code3: 'NZL', name: 'New Zealand', countryNumber: '554' },
  { code: 'NI', code3: 'NIC', name: 'Nicaragua', countryNumber: '558' },
  { code: 'NE', code3: 'NER', name: 'Niger', countryNumber: '562' },
  { code: 'NG', code3: 'NGA', name: 'Nigeria', countryNumber: '566' },
  { code: 'NU', code3: 'NIU', name: 'Niue', countryNumber: '570' },
  { code: 'NF', code3: 'NFK', name: 'Norfolk Island', countryNumber: '574' },
  { code: 'KP', code3: 'PRK', name: 'North Korea', countryNumber: '408' },
  {
    code: 'MP',
    code3: 'MNP',
    name: 'Northern Mariana Islands',
    countryNumber: '580',
  },
  { code: 'NO', code3: 'NOR', name: 'Norway', countryNumber: '578' },
  { code: 'OM', code3: 'OMN', name: 'Oman', countryNumber: '512' },
  { code: 'PK', code3: 'PAK', name: 'Pakistan', countryNumber: '586' },
  { code: 'PW', code3: 'PLW', name: 'Palau', countryNumber: '585' },
  {
    code: 'PS',
    code3: 'PSE',
    name: 'Palestine, State of',
    countryNumber: '275',
  },
  { code: 'PA', code3: 'PAN', name: 'Panama', countryNumber: '591' },
  { code: 'PG', code3: 'PNG', name: 'Papua New Guinea', countryNumber: '598' },
  { code: 'PY', code3: 'PRY', name: 'Paraguay', countryNumber: '600' },
  { code: 'PE', code3: 'PER', name: 'Peru', countryNumber: '604' },
  { code: 'PH', code3: 'PHL', name: 'Philippines', countryNumber: '608' },
  { code: 'PN', code3: 'PCN', name: 'Pitcairn', countryNumber: '612' },
  { code: 'PL', code3: 'POL', name: 'Poland', countryNumber: '616' },
  { code: 'PT', code3: 'PRT', name: 'Portugal', countryNumber: '620' },
  { code: 'PR', code3: 'PRI', name: 'Puerto Rico', countryNumber: '630' },
  { code: 'QA', code3: 'QAT', name: 'Qatar', countryNumber: '634' },
  {
    code: 'MK',
    code3: 'MKD',
    name: 'Republic of North Macedonia',
    countryNumber: '807',
  },
  { code: 'RO', code3: 'ROU', name: 'Romania', countryNumber: '642' },
  {
    code: 'RU',
    code3: 'RUS',
    name: 'Russian Federation',
    countryNumber: '643',
  },
  { code: 'RW', code3: 'RWA', name: 'Rwanda', countryNumber: '646' },
  { code: 'RE', code3: 'REU', name: 'Réunion', countryNumber: '638' },
  { code: 'BL', code3: 'BLM', name: 'Saint Barthélemy', countryNumber: '652' },
  {
    code: 'SH',
    code3: 'SHN',
    name: 'Saint Helena, Ascension, Tristan da Cunha',
    countryNumber: '654',
  },
  {
    code: 'KN',
    code3: 'KNA',
    name: 'Saint Kitts and Nevis',
    countryNumber: '659',
  },
  { code: 'LC', code3: 'LCA', name: 'Saint Lucia', countryNumber: '662' },
  { code: 'MF', code3: 'MAF', name: 'Saint Martin', countryNumber: '663' },
  {
    code: 'PM',
    code3: 'SPM',
    name: 'Saint Pierre and Miquelon',
    countryNumber: '666',
  },
  {
    code: 'VC',
    code3: 'VCT',
    name: 'Saint Vincent and the Grenadines',
    countryNumber: '670',
  },
  { code: 'WS', code3: 'WSM', name: 'Samoa', countryNumber: '882' },
  { code: 'SM', code3: 'SMR', name: 'San Marino', countryNumber: '674' },
  {
    code: 'ST',
    code3: 'STP',
    name: 'Sao Tome and Principe',
    countryNumber: '678',
  },
  { code: 'SA', code3: 'SAU', name: 'Saudi Arabia', countryNumber: '682' },
  { code: 'SN', code3: 'SEN', name: 'Senegal', countryNumber: '686' },
  { code: 'RS', code3: 'SRB', name: 'Serbia', countryNumber: '688' },
  { code: 'SC', code3: 'SYC', name: 'Seychelles', countryNumber: '690' },
  { code: 'SL', code3: 'SLE', name: 'Sierra Leone', countryNumber: '694' },
  { code: 'SG', code3: 'SGP', name: 'Singapore', countryNumber: '702' },
  { code: 'SX', code3: 'SXM', name: 'Sint Maarten', countryNumber: '534' },
  { code: 'SK', code3: 'SVK', name: 'Slovakia', countryNumber: '703' },
  { code: 'SI', code3: 'SVN', name: 'Slovenia', countryNumber: '705' },
  { code: 'SB', code3: 'SLB', name: 'Solomon Islands', countryNumber: '090' },
  { code: 'SO', code3: 'SOM', name: 'Somalia', countryNumber: '706' },
  { code: 'ZA', code3: 'ZAF', name: 'South Africa', countryNumber: '710' },
  {
    code: 'GS',
    code3: 'SGS',
    name: 'South Georgia and the South Sandwich Islands',
    countryNumber: '239',
  },
  { code: 'SS', code3: 'SSD', name: 'South Sudan', countryNumber: '728' },
  { code: 'ES', code3: 'ESP', name: 'Spain', countryNumber: '724' },
  { code: 'LK', code3: 'LKA', name: 'Sri Lanka', countryNumber: '144' },
  { code: 'SD', code3: 'SDN', name: 'Sudan', countryNumber: '729' },
  { code: 'SR', code3: 'SUR', name: 'Suriname', countryNumber: '740' },
  {
    code: 'SJ',
    code3: 'SJM',
    name: 'Svalbard, Jan Mayen',
    countryNumber: '744',
  },
  { code: 'SE', code3: 'SWE', name: 'Sweden', countryNumber: '752' },
  { code: 'CH', code3: 'CHE', name: 'Switzerland', countryNumber: '756' },
  {
    code: 'SY',
    code3: 'SYR',
    name: 'Syrian Arab Republic',
    countryNumber: '760',
  },
  { code: 'TW', code3: 'TWN', name: 'Taiwan', countryNumber: '158' },
  { code: 'TJ', code3: 'TJK', name: 'Tajikistan', countryNumber: '762' },
  {
    code: 'TZ',
    code3: 'TZA',
    name: 'Tanzania, United Republic of',
    countryNumber: '834',
  },
  { code: 'TH', code3: 'THA', name: 'Thailand', countryNumber: '764' },
  { code: 'TL', code3: 'TLS', name: 'Timor-Leste', countryNumber: '626' },
  { code: 'TG', code3: 'TGO', name: 'Togo', countryNumber: '768' },
  { code: 'TK', code3: 'TKL', name: 'Tokelau', countryNumber: '772' },
  { code: 'TO', code3: 'TON', name: 'Tonga', countryNumber: '776' },
  {
    code: 'TT',
    code3: 'TTO',
    name: 'Trinidad and Tobago',
    countryNumber: '780',
  },
  { code: 'TN', code3: 'TUN', name: 'Tunisia', countryNumber: '788' },
  { code: 'TR', code3: 'TUR', name: 'Turkey', countryNumber: '792' },
  { code: 'TM', code3: 'TKM', name: 'Turkmenistan', countryNumber: '795' },
  { code: 'TC', code3: 'TCA', name: 'Turks and Caicos', countryNumber: '796' },
  { code: 'TV', code3: 'TUV', name: 'Tuvalu', countryNumber: '798' },
  { code: 'UG', code3: 'UGA', name: 'Uganda', countryNumber: '800' },
  { code: 'UA', code3: 'UKR', name: 'Ukraine', countryNumber: '804' },
  {
    code: 'AE',
    code3: 'ARE',
    name: 'United Arab Emirates',
    countryNumber: '784',
  },
  { code: 'GB', code3: 'GBR', name: 'United Kingdom', countryNumber: '826' },
  {
    code: 'UM',
    code3: 'UMI',
    name: 'Minor Outlying Islands',
    countryNumber: '581',
  },
  { code: 'US', code3: 'USA', name: 'United States', countryNumber: '840' },
  { code: 'UY', code3: 'URY', name: 'Uruguay', countryNumber: '858' },
  { code: 'UZ', code3: 'UZB', name: 'Uzbekistan', countryNumber: '860' },
  { code: 'VU', code3: 'VUT', name: 'Vanuatu', countryNumber: '548' },
  { code: 'VE', code3: 'VEN', name: 'Venezuela', countryNumber: '862' },
  { code: 'VN', code3: 'VNM', name: 'Viet Nam', countryNumber: '704' },
  {
    code: 'VG',
    code3: 'VGB',
    name: 'British Virgin Islands',
    countryNumber: '092',
  },
  {
    code: 'VI',
    code3: 'VIR',
    name: 'U.S. Virgin Islands',
    countryNumber: '850',
  },
  { code: 'WF', code3: 'WLF', name: 'Wallis and Futuna', countryNumber: '876' },
  { code: 'EH', code3: 'ESH', name: 'Western Sahara', countryNumber: '732' },
  { code: 'YE', code3: 'YEM', name: 'Yemen', countryNumber: '887' },
  { code: 'ZM', code3: 'ZMB', name: 'Zambia', countryNumber: '894' },
  { code: 'ZW', code3: 'ZWE', name: 'Zimbabwe', countryNumber: '716' },
  { code: 'AX', code3: 'ALA', name: 'Åland Islands', countryNumber: '248' },
];
export const trialCountriesToken = new InjectionToken<TrialCountry[]>('Trial Countries');

const trialCountryDictionary: Readonly<TrialCountryDictionary> = Object.fromEntries(
  trialCountries.map((country) => [country.code3, country])
) as Readonly<TrialCountryDictionary>;
export const countryDic: TrialCountryDictionary = trialCountryDictionary;
export const countryDicToken = new InjectionToken<TrialCountryDictionary>('Trials Countries Dictionary');

export const focusCountriesToken = ['USA', 'CHN', 'DEU', 'JPN'];
export const coreCountriesToken = ['ITA', 'CAN', 'FRA', 'ESP', 'BRA', 'MEX', 'KOR', 'AUS', 'TWN', 'GBR'];

export const defaultRegions: Region[] = ['EUCAN', 'IMETA', 'ASKAN', 'LATAM', 'USA', 'JAPAN', 'TCM'];
export const regionsToken = new InjectionToken<Region[]>('Default Regions Available');

export const regionsMap: MeterItem[] = [
  { label: 'EUCAN', value: 0, color: '#34d399' },
  { label: 'IMETA', value: 0, color: '#fbbf24' },
  { label: 'ASKAN', value: 0, color: '#60a5fa' },
  { label: 'LATAM', value: 0, color: '#c084fc' },
  { label: 'USA', value: 0, color: '#30c9dc' },
  { label: 'JAPAN', value: 0, color: '#fa60f7' },
  { label: 'TCM', value: 0, color: '#7EC8FD99' },
];

export const regionsMapToken = new InjectionToken<MeterItem[] | undefined>('Regions Map Available');

export const countriesProviders = [
  {
    provide: trialCountriesToken,
    useValue: trialCountries,
  },
  {
    provide: countryDicToken,
    useValue: countryDic,
  },
  {
    provide: regionsToken,
    useValue: defaultRegions,
  },
  {
    provide: regionsMapToken,
    useValue: regionsMap,
  },
];
